spring.application.name=kbn-backend
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.user.datasource.driver-class-name=com.mysql.jdbc.driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=4b6f52f1a3e94882b013e2a14fd91c8a3c6b2a6d897b08c7db1a7f11f0d2aaf
vapid.public.key=BK9RWKh9AP4OcFeRlDiZatdzTK3oLn6H5TenagiaH5CO8nqyhOCS8YtkyeZe1snDn8KF4ui-6K_XrMSFJlVde6w
vapid.private.key=K-35ojdDFvXmjEWX4B-7--Rnz5rpB8Z8XC3AvR7qxBg

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nautica.atins@gmail.com
spring.mail.password=bfgvbradoigfmgav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=noreply@sendgrid.net
sendgrid.from.name=KBN Admin
app.frontend.url=https://kbn-admin.vercel.app